export const chats = [
  {
    id: 1,
    imgUrl: "/images/img1.jpg",
    name: "Abhay Kumar",
    dateTime: "10:56",
    lastMsg: "How to make whatsapp clone using HTML and CSS",
    unreadMsgCount: 0,
  },
  {
    id: 2,
    imgUrl: "/images/img2.jpg",
    name: "Rahul Khanna",
    dateTime: "09:25",
    lastMsg: "Hello there, found you on youtube",
    unreadMsgCount: 1,
  },
  {
    id: 3,
    imgUrl: "/images/img3.jpg",
    name: "Olivia",
    dateTime: "yesterday",
    lastMsg: "Send for processing",
    unreadMsgCount: 2,
  },
  {
    id: 4,
    imgUrl: "/images/img4.jpg",
    name: "Amelia",
    dateTime: "yesterday",
    lastMsg: "Hello",
    unreadMsgCount: 0,
  },
  {
    id: 5,
    imgUrl: "/images/img5.jpg",
    name: "Rahul Kumar",
    dateTime: "yesterday",
    lastMsg: "oh Ok, Hope you get better soon",
    unreadMsgCount: 0,
  },
  {
    id: 6,
    imgUrl: "/images/img6.jpg",
    name: "Joseph",
    dateTime: "08/10/2021",
    lastMsg: "nice to talk to you",
    unreadMsgCount: 0,
  },
  {
    id: 7,
    imgUrl: "/images/img7.jpg",
    name: "Diana Prince",
    dateTime: "08/10/2021",
    lastMsg: "nice to talk to you",
    unreadMsgCount: 0,
  },
  {
    id: 8,
    imgUrl: "/images/img8.jpg",
    name: "Kabir",
    dateTime: "07/10/2021",
    lastMsg: "Happy Birthday",
    unreadMsgCount: 0,
  },
  {
    id: 9,
    imgUrl: "/images/img9.jpg",
    name: "Alina Smith",
    dateTime: "05/10/2021",
    lastMsg: "Thank you for the help",
    unreadMsgCount: 0,
  },
  {
    id: 10,
    imgUrl: "/images/img2.jpg",
    name: "Barkha",
    dateTime: "02/10/2021",
    lastMsg: "Have you watched Drishyam",
    unreadMsgCount: 0,
  },

  {
    id: 11,
    imgUrl: "/images/img7.jpg",
    name: "Diana Prince",
    dateTime: "08/10/2021",
    lastMsg: "nice to talk to you",
    unreadMsgCount: 0,
  },
  {
    id: 12,
    imgUrl: "/images/img8.jpg",
    name: "Kabir",
    dateTime: "07/10/2021",
    lastMsg: "Happy Birthday",
    unreadMsgCount: 0,
  },
  {
    id: 13,
    imgUrl: "/images/img9.jpg",
    name: "Alina Smith",
    dateTime: "05/10/2021",
    lastMsg: "Thank you for the help",
    unreadMsgCount: 0,
  },
  {
    id: 14,
    imgUrl: "/images/img2.jpg",
    name: "Barkha",
    dateTime: "02/10/2021",
    lastMsg: "Have you watched Drishyam",
    unreadMsgCount: 0,
  },
];
