export const chats = [
  {
    id: 1,
    imgUrl: "/images/img1.jpg",
    name: "Abhay Kumar",
    dateTime: "10:56",
    lastMsg: "How to make whatsapp clone using HTML and CSS",
    unreadMsgCount: 0,
  },
  {
    id: 2,
    imgUrl: "/images/img2.jpg",
    name: "Rahul Khanna",
    dateTime: "09:25",
    lastMsg: "Hello there, found you on youtube",
    unreadMsgCount: 1,
  },
  {
    id: 3,
    imgUrl: "/images/img3.jpg",
    name: "Olivia",
    dateTime: "yesterday",
    lastMsg: "Send for processing",
    unreadMsgCount: 2,
  },
  {
    id: 4,
    imgUrl: "/images/img4.jpg",
    name: "Amelia",
    dateTime: "yesterday",
    lastMsg: "Hello",
    unreadMsgCount: 0,
  },
  {
    id: 5,
    imgUrl: "/images/img5.jpg",
    name: "Rahul Kumar",
    dateTime: "yesterday",
    lastMsg: "oh Ok, Hope you get better soon",
    unreadMsgCount: 0,
  },
  {
    id: 6,
    imgUrl: "/images/img6.jpg",
    name: "Joseph",
    dateTime: "08/10/2021",
    lastMsg: "nice to talk to you",
    unreadMsgCount: 0,
  },
  {
    id: 7,
    imgUrl: "/images/img7.jpg",
    name: "Diana Prince",
    dateTime: "08/10/2021",
    lastMsg: "nice to talk to you",
    unreadMsgCount: 0,
  },
  {
    id: 8,
    imgUrl: "/images/img8.jpg",
    name: "Kabir",
    dateTime: "07/10/2021",
    lastMsg: "Happy Birthday",
    unreadMsgCount: 0,
  },
  {
    id: 9,
    imgUrl: "/images/img9.jpg",
    name: "Alina Smith",
    dateTime: "05/10/2021",
    lastMsg: "Thank you for the help",
    unreadMsgCount: 0,
  },
  {
    id: 10,
    imgUrl: "/images/img2.jpg",
    name: "Barkha",
    dateTime: "02/10/2021",
    lastMsg: "Have you watched Drishyam",
    unreadMsgCount: 0,
  },

  {
    id: 11,
    imgUrl: "/images/img7.jpg",
    name: "Diana Prince",
    dateTime: "08/10/2021",
    lastMsg: "nice to talk to you",
    unreadMsgCount: 0,
  },
  {
    id: 12,
    imgUrl: "/images/img8.jpg",
    name: "Kabir",
    dateTime: "07/10/2021",
    lastMsg: "Happy Birthday",
    unreadMsgCount: 0,
  },
  {
    id: 13,
    imgUrl: "/images/img9.jpg",
    name: "Alina Smith",
    dateTime: "05/10/2021",
    lastMsg: "Thank you for the help",
    unreadMsgCount: 0,
  },
  {
    id: 14,
    imgUrl: "/images/img2.jpg",
    name: "Barkha",
    dateTime: "02/10/2021",
    lastMsg: "Have you watched Drishyam",
    unreadMsgCount: 0,
  },
];

export const messages = [
  { id: 1, msg: "Hi", time: "12:15", inMsg: true },
  { id: 2, msg: "Hello", time: "12:15", inMsg: false },
  { id: 3, msg: "Lorem ipsum dolor sit amet.", time: "12:15", inMsg: true },
  {
    id: 4,
    msg: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium, esse?",
    time: "12:15",
    inMsg: false,
  },
  { id: 5, msg: "Lorem, ipsum dolor.", time: "12:15", inMsg: true },
  {
    id: 6,
    msg: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed error ut quidem esse aliquam tempore.",
    time: "12:15",
    inMsg: true,
  },
  { id: 7, msg: "OK. good then", time: "12:15", inMsg: false },
  {
    id: 8,
    msg: "Sure, I'll let you know by tommorow EOD",
    time: "12:15",
    inMsg: true,
  },
  { id: 9, msg: "Sounds good to me", time: "12:15", inMsg: false },
  {
    id: 10,
    msg: "BTW Lorem ipsum dolor sit amet consectetur adipisicing.",
    time: "12:15",
    inMsg: true,
  },
  { id: 11, msg: "Oh I see!!!", time: "12:15", inMsg: false },
  { id: 12, msg: "New dates are being proposed", time: "12:15", inMsg: true },
  {
    id: 13,
    msg: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo laboriosam nisi, ipsum nihil modi at eligendi explicabo culpa, nesciunt eius asperiores aut esse omnis voluptates.",
    time: "12:15",
    inMsg: false,
  },
  { id: 14, msg: "Lorem ipsum dolor sit amet.", time: "12:15", inMsg: true },
  {
    id: 15,
    msg: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt modi fuga vel sit.",
    time: "12:15",
    inMsg: false,
  },
  { id: 16, msg: "Haha, good one.", time: "12:15", inMsg: true },
  { id: 17, msg: "See you on sunday!", time: "12:15", inMsg: false },
  { id: 18, msg: "Bye, goodnight", time: "12:15", inMsg: false },
  { id: 19, msg: "Hi", time: "12:15", inMsg: true },
  { id: 20, msg: "Hello Again!", time: "12:15", inMsg: false },
  { id: 21, msg: "Have you completed the task", time: "12:15", inMsg: true },
  { id: 22, msg: "Yes", time: "12:15", inMsg: false },
  { id: 23, msg: "Can you send it to me?", time: "12:15", inMsg: true },
  { id: 24, msg: "There you go", time: "12:15", inMsg: false },
  { id: 25, msg: "Thanks", time: "12:15", inMsg: true },
];
